services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: biblio
      POSTGRES_PASSWORD: biblio_pw
      POSTGRES_DB: biblio_db
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblio -d biblio_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: biblio_logs
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports: ["27018:27017"]
    volumes:
      - mongodata:/data/db
      - ./db-init/mongo:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  mongodata:
